import type { Metadata } from 'next'

import StyledComponentsRegistry from '@/styles/lib/styled/registry'

export const metadata: Metadata = {
  title: 'Travel e-commerce',
  description: 'Generated by create next app',
  keywords: [
    'Viagem',
    'Turismo',
    'Familia',
    'Passagem',
    'Avião',
    'Barco',
    'Cruzeiro',
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StyledComponentsRegistry>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StyledComponentsRegistry>
  )
}
