import type { Metadata } from 'next'

import GlobalStyles from '@/styles/GlobalStyles'
import Providers from '@/styles/lib/styled/providers'

export const metadata: Metadata = {
  title: 'Travel e-commerce',
  description: 'Generated by create next app',
  keywords: [
    'Viagem',
    'Turismo',
    'Familia',
    'Passagem',
    'Avião',
    'Barco',
    'Cruzeiro',
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <GlobalStyles />
          {children}
        </Providers>
      </body>
    </html>
  )
}
