import { AntdRegistry } from '@ant-design/nextjs-registry'
import type { Metadata } from 'next'

import GlobalStyles from '../src/styles/GlobalStyles'
import Providers from '../src/styles/lib/styled/providers'

export interface SearchParams {
  params: {
    pagination: string
  }
}

export const metadata: Metadata = {
  title: 'Travel e-commerce',
  description: 'Generated by create next app',
  keywords: [
    'Viagem',
    'Turismo',
    'Familia',
    'Passagem',
    'Avião',
    'Barco',
    'Cruzeiro',
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Providers>
            <GlobalStyles />
            {children}
          </Providers>
        </AntdRegistry>
      </body>
    </html>
  )
}
